// ═══════════════════════════════════════════════════════════════════════════
// NatIQ Export Utilities - CSV & PDF Generation (jsPDF)
// ═══════════════════════════════════════════════════════════════════════════

import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import ExcelJS from 'exceljs';
import type { Employee, DashboardData, RegulatoryChange } from '@/types/database';

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function escapeCsv(value: unknown): string {
  const str = String(value ?? '');
  if (str.includes(',') || str.includes('"') || str.includes('\n')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

// ─── Shared PDF helpers ─────────────────────────────────────────────────────

const COLORS = {
  primary: [14, 124, 123] as [number, number, number],
  dark: [27, 58, 92] as [number, number, number],
  text: [26, 26, 46] as [number, number, number],
  muted: [120, 120, 140] as [number, number, number],
  compliant: [5, 150, 105] as [number, number, number],
  atRisk: [217, 119, 6] as [number, number, number],
  nonCompliant: [220, 38, 38] as [number, number, number],
};

function addHeader(doc: jsPDF, title: string, subtitle?: string) {
  const pageW = doc.internal.pageSize.getWidth();
  // Top accent bar
  doc.setFillColor(...COLORS.primary);
  doc.rect(0, 0, pageW, 4, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(...COLORS.primary);
  doc.text(title, pageW / 2, 24, { align: 'center' });

  if (subtitle) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(...COLORS.muted);
    doc.text(subtitle, pageW / 2, 32, { align: 'center' });
  }

  // Divider line
  doc.setDrawColor(...COLORS.primary);
  doc.setLineWidth(0.5);
  doc.line(20, 36, pageW - 20, 36);

  return 42; // Y cursor after header
}

function addFooter(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.muted);
    doc.text('Generated by NatIQ — GCC Nationalization Compliance Platform', pageW / 2, pageH - 14, { align: 'center' });
    doc.text('This is an informational document and does not constitute legal or regulatory advice.', pageW / 2, pageH - 9, { align: 'center' });
    doc.text(`Page ${i} of ${pageCount}`, pageW - 20, pageH - 9, { align: 'right' });
  }
}

function addSectionTitle(doc: jsPDF, title: string, y: number): number {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(...COLORS.dark);
  doc.text(title, 20, y);
  doc.setDrawColor(229, 231, 235);
  doc.setLineWidth(0.3);
  doc.line(20, y + 2, doc.internal.pageSize.getWidth() - 20, y + 2);
  return y + 8;
}

// ─── Employee List Export (CSV) ─────────────────────────────────────────────

export function exportEmployeesCSV(employees: Employee[], entityName: string) {
  const headers = ['Name', 'Nationality', 'Is National', 'Job Title', 'Department', 'Contract Type', 'Counts Toward Quota', 'Start Date', 'Salary Band'];
  const rows = employees.map(e => [
    e.full_name, e.nationality, e.is_national ? 'Yes' : 'No',
    e.job_title || '', e.department || '', e.contract_type,
    e.counts_toward_quota ? 'Yes' : 'No', e.start_date || '', e.salary_band || '',
  ]);

  const csv = [headers.map(escapeCsv).join(','), ...rows.map(r => r.map(escapeCsv).join(','))].join('\n');
  const blob = new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8;' });
  downloadBlob(blob, `employees_${entityName.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.csv`);
}

// ─── Compliance Certificate PDF ─────────────────────────────────────────────

export function exportCompliancePDF(data: DashboardData) {
  const { entity, score } = data;
  const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  const doc = new jsPDF();
  let y = addHeader(doc, 'NatIQ Compliance Certificate', `Generated on ${now}`);

  // Entity info table
  y = addSectionTitle(doc, 'Entity Information', y);
  autoTable(doc, {
    startY: y,
    margin: { left: 20, right: 20 },
    theme: 'plain',
    styles: { fontSize: 10, cellPadding: 4 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 50 } },
    body: [
      ['Entity Name', entity.name],
      ['Country', entity.country],
      ['Industry', entity.industry_sector || 'N/A'],
      ['Programme', score.program],
    ],
  });

  y = (doc as any).lastAutoTable.finalY + 10;

  // Compliance score
  const statusColor = score.status === 'COMPLIANT' ? COLORS.compliant : score.status === 'AT_RISK' ? COLORS.atRisk : COLORS.nonCompliant;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(42);
  doc.setTextColor(...COLORS.primary);
  const pageW = doc.internal.pageSize.getWidth();
  doc.text(`${score.ratio.toFixed(1)}%`, pageW / 2, y + 14, { align: 'center' });

  // Status badge
  doc.setFontSize(12);
  doc.setTextColor(...statusColor);
  doc.text(`${score.status} — ${score.band}`, pageW / 2, y + 24, { align: 'center' });

  y += 34;

  // Workforce breakdown
  y = addSectionTitle(doc, 'Workforce Breakdown', y);
  autoTable(doc, {
    startY: y,
    margin: { left: 20, right: 20 },
    head: [['Category', 'Count']],
    body: [
      ['Total Qualifying Workforce', String(score.qualifying_total)],
      ['Qualifying Nationals', String(score.qualifying_nationals)],
      ['Full-time Nationals', String(score.nationals_full_time)],
      ['Part-time Nationals', String(score.nationals_part_time)],
      ['Contract Nationals (excluded)', String(score.nationals_contract)],
      ['Target', `${score.target}%`],
      ['Current Ratio', `${score.ratio.toFixed(1)}%`],
    ],
    headStyles: { fillColor: COLORS.primary, fontSize: 10 },
    styles: { fontSize: 10, cellPadding: 4 },
  });

  y = (doc as any).lastAutoTable.finalY + 10;

  // Department breakdown
  y = addSectionTitle(doc, 'Department Breakdown', y);
  autoTable(doc, {
    startY: y,
    margin: { left: 20, right: 20 },
    head: [['Department', 'Total', 'Nationals', 'Ratio']],
    body: data.department_breakdown.map(d => [d.dept, String(d.total), String(d.nationals), `${d.ratio.toFixed(1)}%`]),
    headStyles: { fillColor: COLORS.primary, fontSize: 10 },
    styles: { fontSize: 10, cellPadding: 4 },
  });

  addFooter(doc);
  doc.save(`compliance_certificate_${entity.name.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`);
}

// ─── Workforce Audit Pack (CSV) ────────────────────────────────────────────

export function exportWorkforceAuditCSV(employees: Employee[], data: DashboardData) {
  const { entity, score, department_breakdown } = data;

  const lines = [
    `Workforce Audit Pack — ${entity.name}`,
    `Generated: ${new Date().toISOString().split('T')[0]}`,
    `Programme: ${score.program}`,
    `Compliance Ratio: ${score.ratio.toFixed(1)}%`,
    `Target: ${score.target}%`,
    `Status: ${score.status}`,
    '',
    'DEPARTMENT SUMMARY',
    'Department,Total,Nationals,Expats,Ratio',
    ...department_breakdown.map(d => `${escapeCsv(d.dept)},${d.total},${d.nationals},${d.expats},${d.ratio.toFixed(1)}%`),
    '',
    'EMPLOYEE ROSTER',
    'Name,Nationality,Is National,Job Title,Department,Contract Type,Counts Toward Quota,Start Date,Salary Band',
    ...employees.map(e => [
      escapeCsv(e.full_name), e.nationality, e.is_national ? 'Yes' : 'No',
      escapeCsv(e.job_title || ''), escapeCsv(e.department || ''), e.contract_type,
      e.counts_toward_quota ? 'Yes' : 'No', e.start_date || '', e.salary_band || '',
    ].join(',')),
  ];

  const csv = lines.join('\n');
  const blob = new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8;' });
  downloadBlob(blob, `workforce_audit_${entity.name.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.csv`);
}

// ─── Forecast Report PDF ───────────────────────────────────────────────────

export function exportForecastPDF(data: DashboardData, forecast: { projected_30d: number; projected_60d: number; projected_90d: number; risk_date: string | null; confidence: string }) {
  const { entity, score } = data;
  const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  const doc = new jsPDF();
  let y = addHeader(doc, '90-Day Compliance Forecast Report', `${entity.name} — Generated ${now}`);

  // Risk alert
  if (forecast.risk_date) {
    doc.setFillColor(254, 243, 199);
    doc.roundedRect(20, y, doc.internal.pageSize.getWidth() - 40, 14, 3, 3, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(...COLORS.atRisk);
    doc.text(`⚠ Risk Date: Compliance may breach minimum around ${forecast.risk_date}`, 26, y + 9);
    y += 22;
  }

  // Metrics table
  autoTable(doc, {
    startY: y,
    margin: { left: 20, right: 20 },
    head: [['Metric', 'Value']],
    body: [
      ['Current Ratio', `${score.ratio.toFixed(1)}%`],
      ['Target', `${score.target}%`],
      ['30-Day Projection', `${forecast.projected_30d.toFixed(1)}%`],
      ['60-Day Projection', `${forecast.projected_60d.toFixed(1)}%`],
      ['90-Day Projection', `${forecast.projected_90d.toFixed(1)}%`],
      ['Confidence', forecast.confidence],
    ],
    headStyles: { fillColor: COLORS.primary, fontSize: 10 },
    styles: { fontSize: 10, cellPadding: 5 },
  });

  addFooter(doc);
  doc.save(`forecast_report_${entity.name.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`);
}

// ─── Regulatory Impact Summary (PDF) ───────────────────────────────────────

export function exportRegulatoryPDF(changes: RegulatoryChange[]) {
  const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const doc = new jsPDF('landscape');
  let y = addHeader(doc, 'Regulatory Impact Summary', `Generated on ${now}`);

  autoTable(doc, {
    startY: y,
    margin: { left: 14, right: 14 },
    head: [['Country', 'Programme', 'Headline', 'Impact', 'Change Type', 'Effective Date', 'Summary']],
    body: changes.map(c => [
      c.country, c.program, c.headline, c.impact_level || '—', c.change_type || '—',
      c.effective_date || '—', c.summary || '',
    ]),
    headStyles: { fillColor: COLORS.primary, fontSize: 9 },
    styles: { fontSize: 8, cellPadding: 3, overflow: 'linebreak' },
    columnStyles: {
      2: { cellWidth: 55 },
      6: { cellWidth: 70 },
    },
  });

  addFooter(doc);
  doc.save(`regulatory_impact_${new Date().toISOString().split('T')[0]}.pdf`);
}

// ─── Regulatory Impact Summary (CSV) ───────────────────────────────────────

export function exportRegulatoryCSV(changes: RegulatoryChange[]) {
  const headers = ['Country', 'Programme', 'Headline', 'Impact Level', 'Change Type', 'Effective Date', 'Detected At', 'Summary'];
  const rows = changes.map(c => [
    c.country, c.program, c.headline, c.impact_level || '', c.change_type || '',
    c.effective_date || '', c.detected_at, c.summary || '',
  ]);

  const csv = [headers.map(escapeCsv).join(','), ...rows.map(r => r.map(escapeCsv).join(','))].join('\n');
  const blob = new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8;' });
  downloadBlob(blob, `regulatory_changes_${new Date().toISOString().split('T')[0]}.csv`);
}

// ═══════════════════════════════════════════════════════════════════════════
// Excel (.xlsx) Exports — ExcelJS with charts & styling
// ═══════════════════════════════════════════════════════════════════════════

const BRAND = { primary: '0E7C7B', dark: '1B3A5C', green: '059669', amber: 'D97706', red: 'DC2626', light: 'F0FDFA' };

async function saveExcelWorkbook(wb: ExcelJS.Workbook, filename: string) {
  const buf = await wb.xlsx.writeBuffer();
  const blob = new Blob([buf], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
  downloadBlob(blob, filename);
}

function styleHeaderRow(ws: ExcelJS.Worksheet) {
  const row = ws.getRow(1);
  row.font = { bold: true, color: { argb: 'FFFFFFFF' }, size: 11 };
  row.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: `FF${BRAND.primary}` } };
  row.alignment = { vertical: 'middle', horizontal: 'center' };
  row.height = 24;
  row.eachCell(cell => {
    cell.border = { bottom: { style: 'thin', color: { argb: 'FF' + BRAND.dark } } };
  });
}

function autoFitColumns(ws: ExcelJS.Worksheet, minWidth = 10, maxWidth = 50) {
  ws.columns.forEach(col => {
    let max = minWidth;
    col.eachCell?.({ includeEmpty: false }, cell => {
      const len = String(cell.value ?? '').length + 2;
      if (len > max) max = Math.min(len, maxWidth);
    });
    col.width = max;
  });
}

// ─── Workforce Audit Excel (multi-sheet with chart) ────────────────────────

export async function exportWorkforceAuditXLSX(employees: Employee[], data: DashboardData) {
  const { entity, score, department_breakdown } = data;
  const wb = new ExcelJS.Workbook();
  wb.creator = 'NatIQ';
  wb.created = new Date();

  // ── Sheet 1: Summary ──
  const wsSummary = wb.addWorksheet('Summary', { properties: { tabColor: { argb: `FF${BRAND.primary}` } } });

  // Title
  wsSummary.mergeCells('A1:B1');
  const titleCell = wsSummary.getCell('A1');
  titleCell.value = `Workforce Audit Pack — ${entity.name}`;
  titleCell.font = { bold: true, size: 16, color: { argb: `FF${BRAND.primary}` } };
  titleCell.alignment = { horizontal: 'left' };

  wsSummary.getCell('A2').value = 'Generated';
  wsSummary.getCell('B2').value = new Date().toISOString().split('T')[0];
  wsSummary.getCell('A3').value = 'Programme';
  wsSummary.getCell('B3').value = score.program;

  // Status with color
  wsSummary.getCell('A4').value = 'Status';
  const statusCell = wsSummary.getCell('B4');
  statusCell.value = `${score.status} — ${score.band}`;
  const statusColor = score.status === 'COMPLIANT' ? BRAND.green : score.status === 'AT_RISK' ? BRAND.amber : BRAND.red;
  statusCell.font = { bold: true, color: { argb: `FF${statusColor}` } };

  // Metrics
  const metrics = [
    ['Compliance Ratio', `${score.ratio.toFixed(1)}%`],
    ['Target', `${score.target}%`],
    ['Qualifying Total', score.qualifying_total],
    ['Qualifying Nationals', score.qualifying_nationals],
    ['Full-time Nationals', score.nationals_full_time],
    ['Part-time Nationals', score.nationals_part_time],
    ['Contract Nationals (excluded)', score.nationals_contract],
  ];
  metrics.forEach(([label, val], i) => {
    const row = i + 6;
    wsSummary.getCell(`A${row}`).value = label as string;
    wsSummary.getCell(`A${row}`).font = { bold: true, color: { argb: `FF${BRAND.dark}` } };
    wsSummary.getCell(`B${row}`).value = val;
  });

  wsSummary.getColumn(1).width = 30;
  wsSummary.getColumn(2).width = 22;

  // ── Sheet 2: Departments with chart ──
  const wsDept = wb.addWorksheet('Departments', { properties: { tabColor: { argb: `FF${BRAND.dark}` } } });
  wsDept.addRow(['Department', 'Total', 'Nationals', 'Expats', 'Ratio (%)']);
  styleHeaderRow(wsDept);

  department_breakdown.forEach(d => {
    const row = wsDept.addRow([d.dept, d.total, d.nationals, d.expats, Number(d.ratio.toFixed(1))]);
    // Color the ratio cell
    const ratioCell = row.getCell(5);
    const ratio = d.ratio;
    ratioCell.font = { bold: true, color: { argb: `FF${ratio >= 20 ? BRAND.green : ratio >= 10 ? BRAND.amber : BRAND.red}` } };
  });

  autoFitColumns(wsDept);

  // Add bar chart for department nationals vs expats
  const deptCount = department_breakdown.length;
  if (deptCount > 0) {
    const chartStartRow = deptCount + 4;
    wsDept.getCell(`A${chartStartRow}`).value = '📊 Department Breakdown Chart';
    wsDept.getCell(`A${chartStartRow}`).font = { bold: true, size: 13, color: { argb: `FF${BRAND.primary}` } };

    // Data summary for visual reference (ExcelJS chart support is limited, so we add a visual data bar)
    department_breakdown.forEach((d, i) => {
      const row = chartStartRow + 2 + i;
      wsDept.getCell(`A${row}`).value = d.dept;
      wsDept.getCell(`B${row}`).value = d.nationals;
      wsDept.getCell(`C${row}`).value = d.expats;

      // Nationals bar (green filled cells)
      const natBar = Math.round(d.nationals / Math.max(...department_breakdown.map(x => x.total)) * 20);
      for (let j = 0; j < natBar; j++) {
        const cell = wsDept.getCell(row, 5 + j);
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: `FF${BRAND.green}` } };
        cell.value = '';
      }
      // Expats bar (amber filled cells)
      const expBar = Math.round(d.expats / Math.max(...department_breakdown.map(x => x.total)) * 20);
      for (let j = 0; j < expBar; j++) {
        const cell = wsDept.getCell(row, 5 + natBar + j);
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: `FF${BRAND.amber}` } };
        cell.value = '';
      }
    });

    // Legend
    const legendRow = chartStartRow + 2 + deptCount + 1;
    const greenLegend = wsDept.getCell(`E${legendRow}`);
    greenLegend.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: `FF${BRAND.green}` } };
    wsDept.getCell(`F${legendRow}`).value = 'Nationals';
    const amberLegend = wsDept.getCell(`G${legendRow}`);
    amberLegend.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: `FF${BRAND.amber}` } };
    wsDept.getCell(`H${legendRow}`).value = 'Expats';
  }

  // ── Sheet 3: Compliance Gauge ──
  const wsGauge = wb.addWorksheet('Compliance Gauge', { properties: { tabColor: { argb: `FF${statusColor}` } } });
  wsGauge.mergeCells('A1:F1');
  wsGauge.getCell('A1').value = 'Compliance Ratio Gauge';
  wsGauge.getCell('A1').font = { bold: true, size: 16, color: { argb: `FF${BRAND.primary}` } };

  // Build a visual gauge bar
  const gaugeWidth = 40;
  const filled = Math.round((score.ratio / 100) * gaugeWidth);
  const targetMark = Math.round((score.target / 100) * gaugeWidth);

  wsGauge.getCell('A3').value = '0%';
  wsGauge.getCell(`A4`).value = 'Current';
  for (let i = 0; i < gaugeWidth; i++) {
    const cell = wsGauge.getCell(3, 2 + i);
    if (i < filled) {
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: `FF${statusColor}` } };
    } else {
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE5E7EB' } };
    }
    cell.value = '';
    // Target marker
    if (i === targetMark) {
      const markerCell = wsGauge.getCell(4, 2 + i);
      markerCell.value = '▲';
      markerCell.font = { bold: true, color: { argb: `FF${BRAND.dark}` }, size: 10 };
      markerCell.alignment = { horizontal: 'center' };
    }
  }
  wsGauge.getCell(3, 2 + gaugeWidth + 1).value = '100%';

  wsGauge.getCell('A6').value = `Current: ${score.ratio.toFixed(1)}%`;
  wsGauge.getCell('A6').font = { bold: true, size: 14, color: { argb: `FF${statusColor}` } };
  wsGauge.getCell('A7').value = `Target: ${score.target}%`;
  wsGauge.getCell('A7').font = { bold: true, size: 12, color: { argb: `FF${BRAND.dark}` } };
  wsGauge.getCell('A8').value = `Gap: ${(score.target - score.ratio).toFixed(1)}%`;
  wsGauge.getCell('A8').font = { size: 12, color: { argb: `FF${score.ratio >= score.target ? BRAND.green : BRAND.red}` } };

  // ── Sheet 4: Employee Roster ──
  const wsEmp = wb.addWorksheet('Employees');
  wsEmp.addRow(['Name', 'Nationality', 'Is National', 'Job Title', 'Department', 'Contract Type', 'Counts Toward Quota', 'Start Date', 'Salary Band']);
  styleHeaderRow(wsEmp);

  employees.forEach(e => {
    const row = wsEmp.addRow([
      e.full_name, e.nationality, e.is_national ? 'Yes' : 'No',
      e.job_title || '', e.department || '', e.contract_type,
      e.counts_toward_quota ? 'Yes' : 'No', e.start_date || '', e.salary_band || '',
    ]);
    // Highlight nationals
    if (e.is_national) {
      row.getCell(3).font = { bold: true, color: { argb: `FF${BRAND.green}` } };
    }
  });

  autoFitColumns(wsEmp);

  await saveExcelWorkbook(wb, `workforce_audit_${entity.name.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.xlsx`);
}

// ─── Regulatory Impact Excel ────────────────────────────────────────────────

export async function exportRegulatoryXLSX(changes: RegulatoryChange[]) {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'NatIQ';

  const ws = wb.addWorksheet('Regulatory Changes', { properties: { tabColor: { argb: `FF${BRAND.primary}` } } });
  ws.addRow(['Country', 'Programme', 'Headline', 'Impact Level', 'Change Type', 'Effective Date', 'Detected At', 'Summary']);
  styleHeaderRow(ws);

  changes.forEach(c => {
    const row = ws.addRow([
      c.country, c.program, c.headline, c.impact_level || '', c.change_type || '',
      c.effective_date || '', c.detected_at, c.summary || '',
    ]);
    // Color impact level
    const impactCell = row.getCell(4);
    const impact = c.impact_level;
    if (impact === 'HIGH') impactCell.font = { bold: true, color: { argb: `FF${BRAND.red}` } };
    else if (impact === 'MEDIUM') impactCell.font = { bold: true, color: { argb: `FF${BRAND.amber}` } };
    else if (impact === 'LOW') impactCell.font = { color: { argb: `FF${BRAND.green}` } };
  });

  // Impact summary chart section
  const highCount = changes.filter(c => c.impact_level === 'HIGH').length;
  const medCount = changes.filter(c => c.impact_level === 'MEDIUM').length;
  const lowCount = changes.filter(c => c.impact_level === 'LOW').length;

  const chartRow = changes.length + 4;
  ws.getCell(`A${chartRow}`).value = '📊 Impact Distribution';
  ws.getCell(`A${chartRow}`).font = { bold: true, size: 13, color: { argb: `FF${BRAND.primary}` } };

  const labels = ['HIGH', 'MEDIUM', 'LOW'];
  const counts = [highCount, medCount, lowCount];
  const colors = [BRAND.red, BRAND.amber, BRAND.green];
  const maxCount = Math.max(...counts, 1);

  labels.forEach((label, i) => {
    const row = chartRow + 2 + i;
    ws.getCell(`A${row}`).value = label;
    ws.getCell(`A${row}`).font = { bold: true, color: { argb: `FF${colors[i]}` } };
    ws.getCell(`B${row}`).value = counts[i];

    const barLen = Math.round((counts[i] / maxCount) * 20);
    for (let j = 0; j < barLen; j++) {
      const cell = ws.getCell(row, 3 + j);
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: `FF${colors[i]}` } };
      cell.value = '';
    }
  });

  autoFitColumns(ws);
  await saveExcelWorkbook(wb, `regulatory_changes_${new Date().toISOString().split('T')[0]}.xlsx`);
}

// ─── Employee List Excel ────────────────────────────────────────────────────

export async function exportEmployeesXLSX(employees: Employee[], entityName: string) {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'NatIQ';

  // Sheet 1: Roster
  const ws = wb.addWorksheet('Employees', { properties: { tabColor: { argb: `FF${BRAND.primary}` } } });
  ws.addRow(['Name', 'Nationality', 'Is National', 'Job Title', 'Department', 'Contract Type', 'Counts Toward Quota', 'Start Date', 'Salary Band']);
  styleHeaderRow(ws);

  employees.forEach(e => {
    const row = ws.addRow([
      e.full_name, e.nationality, e.is_national ? 'Yes' : 'No',
      e.job_title || '', e.department || '', e.contract_type,
      e.counts_toward_quota ? 'Yes' : 'No', e.start_date || '', e.salary_band || '',
    ]);
    if (e.is_national) row.getCell(3).font = { bold: true, color: { argb: `FF${BRAND.green}` } };
  });

  autoFitColumns(ws);

  // Sheet 2: Nationality breakdown chart
  const wsChart = wb.addWorksheet('Breakdown');
  wsChart.getCell('A1').value = 'Nationality Breakdown';
  wsChart.getCell('A1').font = { bold: true, size: 14, color: { argb: `FF${BRAND.primary}` } };

  const nationals = employees.filter(e => e.is_national).length;
  const expats = employees.length - nationals;
  const total = employees.length || 1;

  wsChart.getCell('A3').value = 'Nationals';
  wsChart.getCell('B3').value = nationals;
  wsChart.getCell('C3').value = `${((nationals / total) * 100).toFixed(1)}%`;
  wsChart.getCell('C3').font = { bold: true, color: { argb: `FF${BRAND.green}` } };

  wsChart.getCell('A4').value = 'Expats';
  wsChart.getCell('B4').value = expats;
  wsChart.getCell('C4').value = `${((expats / total) * 100).toFixed(1)}%`;

  // Visual bar
  const natBar = Math.round((nationals / total) * 30);
  const expBar = 30 - natBar;
  for (let i = 0; i < natBar; i++) {
    const cell = wsChart.getCell(6, 1 + i);
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: `FF${BRAND.green}` } };
    cell.value = '';
  }
  for (let i = 0; i < expBar; i++) {
    const cell = wsChart.getCell(6, 1 + natBar + i);
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: `FF${BRAND.amber}` } };
    cell.value = '';
  }

  wsChart.getCell('A8').value = '■ Nationals';
  wsChart.getCell('A8').font = { color: { argb: `FF${BRAND.green}` } };
  wsChart.getCell('B8').value = '■ Expats';
  wsChart.getCell('B8').font = { color: { argb: `FF${BRAND.amber}` } };

  // Department distribution
  const deptMap = new Map<string, { total: number; nationals: number }>();
  employees.forEach(e => {
    const dept = e.department || 'Unassigned';
    const cur = deptMap.get(dept) || { total: 0, nationals: 0 };
    cur.total++;
    if (e.is_national) cur.nationals++;
    deptMap.set(dept, cur);
  });

  let deptRow = 10;
  wsChart.getCell(`A${deptRow}`).value = 'By Department';
  wsChart.getCell(`A${deptRow}`).font = { bold: true, size: 13, color: { argb: `FF${BRAND.dark}` } };
  deptRow += 1;
  wsChart.addRow([]);

  wsChart.getRow(deptRow).values = ['Department', 'Total', 'Nationals', 'Ratio'];
  wsChart.getRow(deptRow).font = { bold: true };
  deptRow++;

  deptMap.forEach((val, dept) => {
    wsChart.getRow(deptRow).values = [dept, val.total, val.nationals, `${((val.nationals / val.total) * 100).toFixed(1)}%`];
    deptRow++;
  });

  autoFitColumns(wsChart);
  await saveExcelWorkbook(wb, `employees_${entityName.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.xlsx`);
}

// ═══════════════════════════════════════════════════════════════════════════
// Audit Log Exports
// ═══════════════════════════════════════════════════════════════════════════

interface AuditLogEntry {
  id: string;
  action: string;
  table_name: string;
  record_id: string | null;
  created_at: string;
  new_data?: any;
  old_data?: any;
}

export function exportAuditLogPDF(logs: AuditLogEntry[], entityName: string) {
  const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const doc = new jsPDF('landscape');
  let y = addHeader(doc, 'Audit Log Report', `${entityName} — Generated ${now}`);

  autoTable(doc, {
    startY: y,
    margin: { left: 14, right: 14 },
    head: [['Timestamp', 'Action', 'Table', 'Record', 'Details']],
    body: logs.map(log => [
      new Date(log.created_at).toLocaleString(),
      log.action,
      log.table_name,
      log.record_id?.substring(0, 8) || '—',
      log.new_data?.full_name || log.old_data?.full_name || '—',
    ]),
    headStyles: { fillColor: COLORS.primary, fontSize: 9 },
    styles: { fontSize: 8, cellPadding: 3 },
    didParseCell: (data: any) => {
      if (data.column.index === 1 && data.section === 'body') {
        const action = data.cell.raw;
        if (action === 'INSERT') data.cell.styles.textColor = COLORS.compliant;
        else if (action === 'DELETE') data.cell.styles.textColor = COLORS.nonCompliant;
        else if (action === 'UPDATE') data.cell.styles.textColor = COLORS.atRisk;
      }
    },
  });

  addFooter(doc);
  doc.save(`audit_log_${entityName.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`);
}

export async function exportAuditLogXLSX(logs: AuditLogEntry[], entityName: string) {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'NatIQ';

  const ws = wb.addWorksheet('Audit Log', { properties: { tabColor: { argb: `FF${BRAND.dark}` } } });
  ws.addRow(['Timestamp', 'Action', 'Table', 'Record ID', 'Name', 'Details']);
  styleHeaderRow(ws);

  logs.forEach(log => {
    const name = log.new_data?.full_name || log.old_data?.full_name || '';
    const row = ws.addRow([
      new Date(log.created_at).toLocaleString(),
      log.action,
      log.table_name,
      log.record_id || '',
      name,
      JSON.stringify(log.new_data || log.old_data || {}).substring(0, 200),
    ]);

    const actionCell = row.getCell(2);
    if (log.action === 'INSERT') actionCell.font = { bold: true, color: { argb: `FF${BRAND.green}` } };
    else if (log.action === 'DELETE') actionCell.font = { bold: true, color: { argb: `FF${BRAND.red}` } };
    else actionCell.font = { bold: true, color: { argb: `FF${BRAND.amber}` } };
  });

  autoFitColumns(ws);

  // Summary sheet
  const wsSummary = wb.addWorksheet('Summary');
  wsSummary.getCell('A1').value = 'Audit Log Summary';
  wsSummary.getCell('A1').font = { bold: true, size: 14, color: { argb: `FF${BRAND.primary}` } };
  wsSummary.getCell('A3').value = 'Entity';
  wsSummary.getCell('B3').value = entityName;
  wsSummary.getCell('A4').value = 'Total Entries';
  wsSummary.getCell('B4').value = logs.length;
  wsSummary.getCell('A5').value = 'Inserts';
  wsSummary.getCell('B5').value = logs.filter(l => l.action === 'INSERT').length;
  wsSummary.getCell('A6').value = 'Updates';
  wsSummary.getCell('B6').value = logs.filter(l => l.action === 'UPDATE').length;
  wsSummary.getCell('A7').value = 'Deletes';
  wsSummary.getCell('B7').value = logs.filter(l => l.action === 'DELETE').length;

  autoFitColumns(wsSummary);
  await saveExcelWorkbook(wb, `audit_log_${entityName.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.xlsx`);
}
