// ═══════════════════════════════════════════════════════════════════════════
// NatIQ Export Utilities - CSV & PDF Generation (jsPDF)
// ═══════════════════════════════════════════════════════════════════════════

import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import ExcelJS from 'exceljs';
import type { Employee, DashboardData, RegulatoryChange } from '@/types/database';

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function escapeCsv(value: unknown): string {
  const str = String(value ?? '');
  if (str.includes(',') || str.includes('"') || str.includes('\n')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

// ─── Shared PDF helpers ─────────────────────────────────────────────────────

const COLORS = {
  primary: [14, 124, 123] as [number, number, number],
  dark: [27, 58, 92] as [number, number, number],
  text: [26, 26, 46] as [number, number, number],
  muted: [120, 120, 140] as [number, number, number],
  compliant: [5, 150, 105] as [number, number, number],
  atRisk: [217, 119, 6] as [number, number, number],
  nonCompliant: [220, 38, 38] as [number, number, number],
};

function addHeader(doc: jsPDF, title: string, subtitle?: string) {
  const pageW = doc.internal.pageSize.getWidth();
  // Top accent bar
  doc.setFillColor(...COLORS.primary);
  doc.rect(0, 0, pageW, 4, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(...COLORS.primary);
  doc.text(title, pageW / 2, 24, { align: 'center' });

  if (subtitle) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(...COLORS.muted);
    doc.text(subtitle, pageW / 2, 32, { align: 'center' });
  }

  // Divider line
  doc.setDrawColor(...COLORS.primary);
  doc.setLineWidth(0.5);
  doc.line(20, 36, pageW - 20, 36);

  return 42; // Y cursor after header
}

function addFooter(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.muted);
    doc.text('Generated by NatIQ — GCC Nationalization Compliance Platform', pageW / 2, pageH - 14, { align: 'center' });
    doc.text('This is an informational document and does not constitute legal or regulatory advice.', pageW / 2, pageH - 9, { align: 'center' });
    doc.text(`Page ${i} of ${pageCount}`, pageW - 20, pageH - 9, { align: 'right' });
  }
}

function addSectionTitle(doc: jsPDF, title: string, y: number): number {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(...COLORS.dark);
  doc.text(title, 20, y);
  doc.setDrawColor(229, 231, 235);
  doc.setLineWidth(0.3);
  doc.line(20, y + 2, doc.internal.pageSize.getWidth() - 20, y + 2);
  return y + 8;
}

// ─── Employee List Export (CSV) ─────────────────────────────────────────────

export function exportEmployeesCSV(employees: Employee[], entityName: string) {
  const headers = ['Name', 'Nationality', 'Is National', 'Job Title', 'Department', 'Contract Type', 'Counts Toward Quota', 'Start Date', 'Salary Band'];
  const rows = employees.map(e => [
    e.full_name, e.nationality, e.is_national ? 'Yes' : 'No',
    e.job_title || '', e.department || '', e.contract_type,
    e.counts_toward_quota ? 'Yes' : 'No', e.start_date || '', e.salary_band || '',
  ]);

  const csv = [headers.map(escapeCsv).join(','), ...rows.map(r => r.map(escapeCsv).join(','))].join('\n');
  const blob = new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8;' });
  downloadBlob(blob, `employees_${entityName.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.csv`);
}

// ─── Compliance Certificate PDF ─────────────────────────────────────────────

export function exportCompliancePDF(data: DashboardData) {
  const { entity, score } = data;
  const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  const doc = new jsPDF();
  let y = addHeader(doc, 'NatIQ Compliance Certificate', `Generated on ${now}`);

  // Entity info table
  y = addSectionTitle(doc, 'Entity Information', y);
  autoTable(doc, {
    startY: y,
    margin: { left: 20, right: 20 },
    theme: 'plain',
    styles: { fontSize: 10, cellPadding: 4 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 50 } },
    body: [
      ['Entity Name', entity.name],
      ['Country', entity.country],
      ['Industry', entity.industry_sector || 'N/A'],
      ['Programme', score.program],
    ],
  });

  y = (doc as any).lastAutoTable.finalY + 10;

  // Compliance score
  const statusColor = score.status === 'COMPLIANT' ? COLORS.compliant : score.status === 'AT_RISK' ? COLORS.atRisk : COLORS.nonCompliant;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(42);
  doc.setTextColor(...COLORS.primary);
  const pageW = doc.internal.pageSize.getWidth();
  doc.text(`${score.ratio.toFixed(1)}%`, pageW / 2, y + 14, { align: 'center' });

  // Status badge
  doc.setFontSize(12);
  doc.setTextColor(...statusColor);
  doc.text(`${score.status} — ${score.band}`, pageW / 2, y + 24, { align: 'center' });

  y += 34;

  // Workforce breakdown
  y = addSectionTitle(doc, 'Workforce Breakdown', y);
  autoTable(doc, {
    startY: y,
    margin: { left: 20, right: 20 },
    head: [['Category', 'Count']],
    body: [
      ['Total Qualifying Workforce', String(score.qualifying_total)],
      ['Qualifying Nationals', String(score.qualifying_nationals)],
      ['Full-time Nationals', String(score.nationals_full_time)],
      ['Part-time Nationals', String(score.nationals_part_time)],
      ['Contract Nationals (excluded)', String(score.nationals_contract)],
      ['Target', `${score.target}%`],
      ['Current Ratio', `${score.ratio.toFixed(1)}%`],
    ],
    headStyles: { fillColor: COLORS.primary, fontSize: 10 },
    styles: { fontSize: 10, cellPadding: 4 },
  });

  y = (doc as any).lastAutoTable.finalY + 10;

  // Department breakdown
  y = addSectionTitle(doc, 'Department Breakdown', y);
  autoTable(doc, {
    startY: y,
    margin: { left: 20, right: 20 },
    head: [['Department', 'Total', 'Nationals', 'Ratio']],
    body: data.department_breakdown.map(d => [d.dept, String(d.total), String(d.nationals), `${d.ratio.toFixed(1)}%`]),
    headStyles: { fillColor: COLORS.primary, fontSize: 10 },
    styles: { fontSize: 10, cellPadding: 4 },
  });

  addFooter(doc);
  doc.save(`compliance_certificate_${entity.name.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`);
}

// ─── Workforce Audit Pack (CSV) ────────────────────────────────────────────

export function exportWorkforceAuditCSV(employees: Employee[], data: DashboardData) {
  const { entity, score, department_breakdown } = data;

  const lines = [
    `Workforce Audit Pack — ${entity.name}`,
    `Generated: ${new Date().toISOString().split('T')[0]}`,
    `Programme: ${score.program}`,
    `Compliance Ratio: ${score.ratio.toFixed(1)}%`,
    `Target: ${score.target}%`,
    `Status: ${score.status}`,
    '',
    'DEPARTMENT SUMMARY',
    'Department,Total,Nationals,Expats,Ratio',
    ...department_breakdown.map(d => `${escapeCsv(d.dept)},${d.total},${d.nationals},${d.expats},${d.ratio.toFixed(1)}%`),
    '',
    'EMPLOYEE ROSTER',
    'Name,Nationality,Is National,Job Title,Department,Contract Type,Counts Toward Quota,Start Date,Salary Band',
    ...employees.map(e => [
      escapeCsv(e.full_name), e.nationality, e.is_national ? 'Yes' : 'No',
      escapeCsv(e.job_title || ''), escapeCsv(e.department || ''), e.contract_type,
      e.counts_toward_quota ? 'Yes' : 'No', e.start_date || '', e.salary_band || '',
    ].join(',')),
  ];

  const csv = lines.join('\n');
  const blob = new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8;' });
  downloadBlob(blob, `workforce_audit_${entity.name.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.csv`);
}

// ─── Forecast Report PDF ───────────────────────────────────────────────────

export function exportForecastPDF(data: DashboardData, forecast: { projected_30d: number; projected_60d: number; projected_90d: number; risk_date: string | null; confidence: string }) {
  const { entity, score } = data;
  const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  const doc = new jsPDF();
  let y = addHeader(doc, '90-Day Compliance Forecast Report', `${entity.name} — Generated ${now}`);

  // Risk alert
  if (forecast.risk_date) {
    doc.setFillColor(254, 243, 199);
    doc.roundedRect(20, y, doc.internal.pageSize.getWidth() - 40, 14, 3, 3, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(...COLORS.atRisk);
    doc.text(`⚠ Risk Date: Compliance may breach minimum around ${forecast.risk_date}`, 26, y + 9);
    y += 22;
  }

  // Metrics table
  autoTable(doc, {
    startY: y,
    margin: { left: 20, right: 20 },
    head: [['Metric', 'Value']],
    body: [
      ['Current Ratio', `${score.ratio.toFixed(1)}%`],
      ['Target', `${score.target}%`],
      ['30-Day Projection', `${forecast.projected_30d.toFixed(1)}%`],
      ['60-Day Projection', `${forecast.projected_60d.toFixed(1)}%`],
      ['90-Day Projection', `${forecast.projected_90d.toFixed(1)}%`],
      ['Confidence', forecast.confidence],
    ],
    headStyles: { fillColor: COLORS.primary, fontSize: 10 },
    styles: { fontSize: 10, cellPadding: 5 },
  });

  addFooter(doc);
  doc.save(`forecast_report_${entity.name.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`);
}

// ─── Regulatory Impact Summary (PDF) ───────────────────────────────────────

export function exportRegulatoryPDF(changes: RegulatoryChange[]) {
  const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const doc = new jsPDF('landscape');
  let y = addHeader(doc, 'Regulatory Impact Summary', `Generated on ${now}`);

  autoTable(doc, {
    startY: y,
    margin: { left: 14, right: 14 },
    head: [['Country', 'Programme', 'Headline', 'Impact', 'Change Type', 'Effective Date', 'Summary']],
    body: changes.map(c => [
      c.country, c.program, c.headline, c.impact_level || '—', c.change_type || '—',
      c.effective_date || '—', c.summary || '',
    ]),
    headStyles: { fillColor: COLORS.primary, fontSize: 9 },
    styles: { fontSize: 8, cellPadding: 3, overflow: 'linebreak' },
    columnStyles: {
      2: { cellWidth: 55 },
      6: { cellWidth: 70 },
    },
  });

  addFooter(doc);
  doc.save(`regulatory_impact_${new Date().toISOString().split('T')[0]}.pdf`);
}

// ─── Regulatory Impact Summary (CSV) ───────────────────────────────────────

export function exportRegulatoryCSV(changes: RegulatoryChange[]) {
  const headers = ['Country', 'Programme', 'Headline', 'Impact Level', 'Change Type', 'Effective Date', 'Detected At', 'Summary'];
  const rows = changes.map(c => [
    c.country, c.program, c.headline, c.impact_level || '', c.change_type || '',
    c.effective_date || '', c.detected_at, c.summary || '',
  ]);

  const csv = [headers.map(escapeCsv).join(','), ...rows.map(r => r.map(escapeCsv).join(','))].join('\n');
  const blob = new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8;' });
  downloadBlob(blob, `regulatory_changes_${new Date().toISOString().split('T')[0]}.csv`);
}

// ═══════════════════════════════════════════════════════════════════════════
// Excel (.xlsx) Exports — Multi-sheet workbooks
// ═══════════════════════════════════════════════════════════════════════════

function saveWorkbook(wb: XLSX.WorkBook, filename: string) {
  const buf = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
  const blob = new Blob([buf], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
  downloadBlob(blob, filename);
}

function setColumnWidths(ws: XLSX.WorkSheet, widths: number[]) {
  ws['!cols'] = widths.map(w => ({ wch: w }));
}

// ─── Workforce Audit Excel (multi-sheet) ────────────────────────────────────

export function exportWorkforceAuditXLSX(employees: Employee[], data: DashboardData) {
  const { entity, score, department_breakdown } = data;
  const wb = XLSX.utils.book_new();

  // Sheet 1: Summary
  const summaryData = [
    ['Workforce Audit Pack', entity.name],
    ['Generated', new Date().toISOString().split('T')[0]],
    ['Programme', score.program],
    ['Compliance Ratio', `${score.ratio.toFixed(1)}%`],
    ['Target', `${score.target}%`],
    ['Status', score.status],
    ['Band', score.band],
    [],
    ['Qualifying Total', score.qualifying_total],
    ['Qualifying Nationals', score.qualifying_nationals],
    ['Full-time Nationals', score.nationals_full_time],
    ['Part-time Nationals', score.nationals_part_time],
    ['Contract Nationals (excluded)', score.nationals_contract],
  ];
  const wsSummary = XLSX.utils.aoa_to_sheet(summaryData);
  setColumnWidths(wsSummary, [30, 20]);
  XLSX.utils.book_append_sheet(wb, wsSummary, 'Summary');

  // Sheet 2: Department Breakdown
  const deptHeaders = ['Department', 'Total', 'Nationals', 'Expats', 'Ratio (%)'];
  const deptRows = department_breakdown.map(d => [d.dept, d.total, d.nationals, d.expats, Number(d.ratio.toFixed(1))]);
  const wsDept = XLSX.utils.aoa_to_sheet([deptHeaders, ...deptRows]);
  setColumnWidths(wsDept, [25, 10, 12, 10, 12]);
  XLSX.utils.book_append_sheet(wb, wsDept, 'Departments');

  // Sheet 3: Employee Roster
  const empHeaders = ['Name', 'Nationality', 'Is National', 'Job Title', 'Department', 'Contract Type', 'Counts Toward Quota', 'Start Date', 'Salary Band'];
  const empRows = employees.map(e => [
    e.full_name, e.nationality, e.is_national ? 'Yes' : 'No',
    e.job_title || '', e.department || '', e.contract_type,
    e.counts_toward_quota ? 'Yes' : 'No', e.start_date || '', e.salary_band || '',
  ]);
  const wsEmp = XLSX.utils.aoa_to_sheet([empHeaders, ...empRows]);
  setColumnWidths(wsEmp, [22, 14, 12, 20, 16, 14, 18, 12, 12]);
  XLSX.utils.book_append_sheet(wb, wsEmp, 'Employees');

  saveWorkbook(wb, `workforce_audit_${entity.name.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.xlsx`);
}

// ─── Regulatory Impact Excel ────────────────────────────────────────────────

export function exportRegulatoryXLSX(changes: RegulatoryChange[]) {
  const wb = XLSX.utils.book_new();
  const headers = ['Country', 'Programme', 'Headline', 'Impact Level', 'Change Type', 'Effective Date', 'Detected At', 'Summary'];
  const rows = changes.map(c => [
    c.country, c.program, c.headline, c.impact_level || '', c.change_type || '',
    c.effective_date || '', c.detected_at, c.summary || '',
  ]);
  const ws = XLSX.utils.aoa_to_sheet([headers, ...rows]);
  setColumnWidths(ws, [10, 20, 35, 14, 22, 14, 14, 50]);
  XLSX.utils.book_append_sheet(wb, ws, 'Regulatory Changes');
  saveWorkbook(wb, `regulatory_changes_${new Date().toISOString().split('T')[0]}.xlsx`);
}

// ─── Employee List Excel ────────────────────────────────────────────────────

export function exportEmployeesXLSX(employees: Employee[], entityName: string) {
  const wb = XLSX.utils.book_new();
  const headers = ['Name', 'Nationality', 'Is National', 'Job Title', 'Department', 'Contract Type', 'Counts Toward Quota', 'Start Date', 'Salary Band'];
  const rows = employees.map(e => [
    e.full_name, e.nationality, e.is_national ? 'Yes' : 'No',
    e.job_title || '', e.department || '', e.contract_type,
    e.counts_toward_quota ? 'Yes' : 'No', e.start_date || '', e.salary_band || '',
  ]);
  const ws = XLSX.utils.aoa_to_sheet([headers, ...rows]);
  setColumnWidths(ws, [22, 14, 12, 20, 16, 14, 18, 12, 12]);
  XLSX.utils.book_append_sheet(wb, ws, 'Employees');
  saveWorkbook(wb, `employees_${entityName.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.xlsx`);
}
